### ISSUE TITLE
Error with MoviePy

### ISSUE THREAD

**Issue by ghost** [Adam-Jimenez/auddit#15]
`Current Task: generate_video
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/VideoClip.py", line 1168, in __init__
    subprocess_call(cmd, logger=None)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert: unable to read font `Amiri-regular' @ warning/annotate.c/RenderType/960.
convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1823.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/562.
convert: no images defined `PNG32:/tmp/tmpy1zr5as3.png' @ error/convert.c/ConvertImageCommand/3273.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 28, in <module>
    pipeline.execute(subreddit='askreddit', nsfw=False, comment_limit=20)
  File "src/main.py", line 24, in execute
    task(self.context)
  File "/root/auddit/src/tasks/generate_video/task.py", line 62, in generate_video
    clips.append(generate_title(post.title, post.title_audio))
  File "/root/auddit/src/tasks/generate_video/task.py", line 20, in generate_title
    txt_clip = TextClip(wrapped_text,fontsize=font_size, font=FONT, color=TITLE_FONT_COLOR, align="west")
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/VideoClip.py", line 1177, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: unable to read font `Amiri-regular' @ warning/annotate.c/RenderType/960.
convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1823.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/562.
convert: no images defined `PNG32:/tmp/tmpy1zr5as3.png' @ error/convert.c/ConvertImageCommand/3273.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
`
I have ImageMagick installed and have tried various methods to fix. I have no idea what the issue is.

**Comment by Adam-Jimenez** [comment]
Its probably due to the fact that it doesn't find the Amiri-regular font on your system. One solution would be to replace it with a font and put it in the assets directory, as done with Copse.ttf

**Comment by ghost** [comment]
So, i changed the font in the task.py file, but it doesnt detect it..

**Comment by Adam-Jimenez** [comment]
I did not try to make it work on Windows, I have no clue.

**Comment by ghost** [comment]
I am using ubuntu, I have never used imagemagick before

**Comment by Adam-Jimenez** [comment]
which font did you set? Are you sure its on your system?

**Comment by ghost** [comment]
yes, apparently my imagemagick doesnt have any delegates installed for font or image support, and I cannot find where to add them :). No support or anything

**Comment by Mafin-dev** [comment]
I changed the font to "Arial" and the errors are gone. Why is MoviePy Linux only? I mean... just make it open for everyone? What is the deal with this exotic font?
