### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by aggin23** [Adam-Jimenez/auddit#20]
Traceback (most recent call last):
  File "C:\Users\Meridius\Desktop\redditbot\src\tasks\text_to_speech\task.py", line 24, in save_tts
    with open(path, "wb") as out_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/audio/7aefc4c34d8c7f5f466a39ee63189bef.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Meridius/Desktop/redditbot/src/main.py", line 28, in <module>
    pipeline.execute(subreddit='askreddit', nsfw=False, comment_limit=20)
  File "C:/Users/Meridius/Desktop/redditbot/src/main.py", line 24, in execute
    task(self.context)
  File "C:\Users\Meridius\Desktop\redditbot\src\tasks\text_to_speech\task.py", line 39, in tts
    post.title_audio = save_tts(post.title)
  File "C:\Users\Meridius\Desktop\redditbot\src\tasks\text_to_speech\task.py", line 29, in save_tts
    return save_gtts(text)
  File "C:\Users\Meridius\Desktop\redditbot\src\tasks\text_to_speech\task.py", line 34, in save_gtts
    tts.save(path)
  File "C:\Users\Meridius\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gtts\tts.py", line 294, in save
    with open(str(savefile), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/audio/4472f828-99bd-4497-bf96-954e61731b50.mp3'

**Comment by THamza** [comment]
Hello, I was wondering if this was solved ? thanks
