### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by alphanumericaltycoon** [Adam-Jimenez/auddit#23]
Hi, any advice on how I can fix the below errors. I am running Kali Linux as my OS. I have already set REDDIT_CLIENT_ID and REDDIT_CLIENT_SECRET using the **export** command in the terminal and confirming with **echo**.

                                                                                                                  
```
┌──(kali㉿kali)-[~/Desktop/auddit]
└─$ python3 src/main.py         
Current Task: get_hottest_post
Current Task: tts
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
Current Task: generate_video
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/home/kali/.local/lib/python3.9/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmpw_lr5lrb.txt' @ error/property.c/InterpretImageProperties/3706.
convert-im6.q16: no images defined `PNG32:/tmp/tmp8rngpnz4.png' @ error/convert.c/ConvertImageCommand/3229.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/auddit/src/main.py", line 28, in <module>
    pipeline.execute(subreddit='askreddit', nsfw=False, comment_limit=20)
  File "/home/kali/Desktop/auddit/src/main.py", line 24, in execute
    task(self.context)
  File "/home/kali/Desktop/auddit/src/tasks/generate_video/task.py", line 62, in generate_video
    clips.append(generate_title(post.title, post.title_audio))
  File "/home/kali/Desktop/auddit/src/tasks/generate_video/task.py", line 20, in generate_title
    txt_clip = TextClip(wrapped_text,fontsize=font_size, font=FONT, color=TITLE_FONT_COLOR, align="west")
  File "/home/kali/.local/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmpw_lr5lrb.txt' @ error/property.c/InterpretImageProperties/3706.
convert-im6.q16: no images defined `PNG32:/tmp/tmp8rngpnz4.png' @ error/convert.c/ConvertImageCommand/3229.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/auddit]
└─$                                

```

(I have no idea why it keeps saying ImageMagick is not installed as it definitely is!)

Any help is greatly appreciated.

**Comment by alphanumericaltycoon** [comment]
And if it helps this is what I get when I run **test_reddit.py**:
```
┌──(kali㉿kali)-[~/Desktop/auddit]
└─$ python3 -m unittest test/test_reddit.py                                                                       1 ⨯
What is your guilty sexual pleasure and why?
.
----------------------------------------------------------------------
Ran 1 test in 4.751s

OK
```

**Comment by Adam-Jimenez** [comment]
It seems to be imagemagick configurations in certain environments that prevent the conversion, check the response to this to see if it helps https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion

**Comment by alphanumericaltycoon** [comment]
Hi, thanks for your prompt reply. I'm not too familiar with imagemagick and new to Linux so I couldn't figure out what bit to change based on that conversation thread. So I ended up just deleting policy.xml and replacing it with a blank file.

The good news is that it ran **main.py** file and generated a video (5mb file). When I play the video the audio seems to be stitched together fine but the screen does not change beyond the opening title. I'm guessing this is still an issue with imagemagick or is there something else I could try?

Thanks

```
                                                                                                                      
┌──(kali㉿kali)-[~/Desktop/auddit]
└─$ python3 src/main.py 
Current Task: get_hottest_post
Current Task: tts
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
TTS Rate limit reached - Fallback on Google text-to-speech
Current Task: generate_video
Moviepy - Building video data/video/f1e6e51f-6ed6-4ec9-85fd-89061906068e.mp4.
MoviePy - Writing audio in f1e6e51f-6ed6-4ec9-85fd-89061906068eTEMP_MPY_wvf_snd.mp3
MoviePy - Done.                                                                                                       
Moviepy - Writing video data/video/f1e6e51f-6ed6-4ec9-85fd-89061906068e.mp4
```

**Comment by Adam-Jimenez** [comment]
Hmm, i assume imagemagick didn't like the config being deleted, you can always generating a video from the documentation to see if that works, if it doesn't it probably confirms that imagemagick is the problem: https://zulko.github.io/moviepy/examples/moving_letters.html

**Comment by alphanumericaltycoon** [comment]
Is there any chance you could share I copy of your policy.xml file so I could compare it? Probably located in /etc/ImageMagick-6/

Many thanks

Edit - I'm not sure why this morning the script is acting up. 

Current Task: get_hottest_post
Traceback (most recent call last):
  File "/home/kali/Desktop/auddit/src/main.py", line 28, in <module>
    pipeline.execute(subreddit='askreddit', nsfw=False, comment_limit=20)
  File "/home/kali/Desktop/auddit/src/main.py", line 24, in execute
    task(self.context)
  File "/home/kali/Desktop/auddit/src/tasks/scrape_reddit/task.py", line 40, in get_hottest_post
    comment_output.author = comment.author.name
AttributeError: 'NoneType' object has no attribute 'name'

VM's are weird!

**Comment by Adam-Jimenez** [comment]
You found a bug, this error happens when a comment is made by a deleted account. I am using ImageMagick-7 with following policy:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policymap [
  <!ELEMENT policymap (policy)*>
  <!ATTLIST policymap xmlns CDATA #FIXED ''>
  <!ELEMENT policy EMPTY>
  <!ATTLIST policy xmlns CDATA #FIXED '' domain NMTOKEN #REQUIRED
    name NMTOKEN #IMPLIED pattern CDATA #IMPLIED rights NMTOKEN #IMPLIED
    stealth NMTOKEN #IMPLIED value CDATA #IMPLIED>
]>
<!--
  Configure ImageMagick policies.

  Domains include system, delegate, coder, filter, path, or resource.

  Rights include none, read, write, execute and all.  Use | to combine them,
  for example: "read | write" to permit read from, or write to, a path.

  Use a glob expression as a pattern.

  Suppose we do not want users to process MPEG video images:

    <policy domain="delegate" rights="none" pattern="mpeg:decode" />

  Here we do not want users reading images from HTTP:

    <policy domain="coder" rights="none" pattern="HTTP" />

  The /repository file system is restricted to read only.  We use a glob
  expression to match all paths that start with /repository:

    <policy domain="path" rights="read" pattern="/repository/*" />

  Lets prevent users from executing any image filters:

    <policy domain="filter" rights="none" pattern="*" />

  Any large image is cached to disk rather than memory:

    <policy domain="resource" name="area" value="1GP"/>

  Use the default system font unless overwridden by the application:

    <policy domain="system" name="font" value="/usr/share/fonts/favorite.ttf"/>

  Define arguments for the memory, map, area, width, height and disk resources
  with SI prefixes (.e.g 100MB).  In addition, resource policies are maximums
  for each instance of ImageMagick (e.g. policy memory limit 1GB, -limit 2GB
  exceeds policy maximum so memory limit is 1GB).

  Rules are processed in order.  Here we want to restrict ImageMagick to only
  read or write a small subset of proven web-safe image types:

    <policy domain="delegate" rights="none" pattern="*" />
    <policy domain="filter" rights="none" pattern="*" />
    <policy domain="coder" rights="none" pattern="*" />
    <policy domain="coder" rights="read|write" pattern="{GIF,JPEG,PNG,WEBP}" />
-->
<policymap>
  <!-- <policy domain="resource" name="temporary-path" value="/tmp"/> -->
  <!-- <policy domain="resource" name="memory" value="2GiB"/> -->
  <!-- <policy domain="resource" name="map" value="4GiB"/> -->
  <!-- <policy domain="resource" name="width" value="10KP"/> -->
  <!-- <policy domain="resource" name="height" value="10KP"/> -->
  <!-- <policy domain="resource" name="list-length" value="128"/> -->
  <!-- <policy domain="resource" name="area" value="100MP"/> -->
  <!-- <policy domain="resource" name="disk" value="16EiB"/> -->
  <!-- <policy domain="resource" name="file" value="768"/> -->
  <!-- <policy domain="resource" name="thread" value="4"/> -->
  <!-- <policy domain="resource" name="throttle" value="0"/> -->
  <!-- <policy domain="resource" name="time" value="3600"/> -->
  <!-- <policy domain="coder" rights="none" pattern="MVG" /> -->
  <!-- <policy domain="module" rights="none" pattern="{PS,PDF,XPS}" /> -->
  <!-- <policy domain="delegate" rights="none" pattern="HTTPS" /> -->
  <!-- <policy domain="path" rights="none" pattern="@*" /> -->
  <!-- <policy domain="cache" name="memory-map" value="anonymous"/> -->
  <!-- <policy domain="cache" name="synchronize" value="True"/> -->
  <!-- <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/> -->
  <!-- <policy domain="system" name="max-memory-request" value="256MiB"/> -->
  <!-- <policy domain="system" name="shred" value="2"/> -->
  <!-- <policy domain="system" name="precision" value="6"/> -->
  <!-- <policy domain="system" name="font" value="/path/to/unicode-font.ttf"/> -->
  <policy domain="delegate" rights="none" pattern="gs" />
</policymap>
```

**Comment by alphanumericaltycoon** [comment]
Thanks for sharing your file. I got it to work - yay! I removed the auto-upload and clean bit in the script because I wanted to manually deal with those parts. Someone may have already asked this but is it possible to direct the script to a particular post rather than automatically finding the most popular? Many thanks and awesome work!

**Comment by Adam-Jimenez** [comment]
Yup, check out the docs for PRAW (reddit api client) https://praw.readthedocs.io/en/stable/tutorials/comments.html
